### PR TITLE
Add colors for Git

### PR DESCRIPTION
**Pull request by phanect**
This Pull Request adds coloring for Git.

I referred [git.less](https://github.com/atom/atom/blob/master/packages/one-light-ui/styles/git.less) and [ui-variables.less](https://github.com/atom/atom/blob/master/packages/one-light-ui/styles/ui-variables.less#L19) from Atom's stylesheets.

screenshot of new coloring in treeview

### CODE REVIEW

**Comment by phanect** [comment]
I have updated the branch so that it no longer conflicts with `master`.

**Comment by akamud** [comment]
Can you ellaborate a little bit more on what exactly did you change? The generated file is minified, so I can't see what you changed and the reason.

**Comment by phanect** [comment]
Thanks for the review.

You can see the readable diffs by reviewing the commits rather than viewing on Changes tab.

In [d3baa03](https://github.com/akamud/vscode-theme-onelight/commit/d3baa036382c406f6fa6ca6e62a33576931ee897), I just formatted JSON.

[5387369](https://github.com/akamud/vscode-theme-onelight/commit/53873690fa7d5fe0c13854441e8e096be4ab1ae7) includes the main changes. In this commit, I have changed the file name colors by git tracking status.
For example, if the files includes changes which is not committed yet, the color of file names should be #2db448.

**Comment by phanect** [comment]
FYI here's document for the each property I changed this time:
https://code.visualstudio.com/api/references/theme-color#git-colors

**Comment by phanect** [comment]
Since this PR is left open without any responses, I'm closing this PR.

**Pull request closed without merging**
