### PR TITLE
Add missing "selectionHighlightBackground" key

### PR DESCRIPTION
**Pull request by andreynering**
This is the key that highlights other identical words (those you can follow which command+D) when you select one.

The default was too close to white, almost invisible. Changing to a slightly darker grey.

### CODE REVIEW

**Comment by andreynering** [comment]
@akamud Closed without a comment?

**Comment by akamud** [comment]
Sorry about that. I just released a new version today and the original issue seems fixed. Can you confirm or did I misunderstand the issue?

**Comment by andreynering** [comment]
@akamud I just updated and the selection is still too light for me, too similar to white, hard to see.

And the `selectionHighlightBackground` key is still on the `OneLight.json`: https://raw.githubusercontent.com/akamud/vscode-theme-onelight/master/themes/OneLight.json

**Comment by akamud** [comment]
Can you please attach some screenshots? When I was testing the editor was using a dark color for me. Maybe I'm missing something.

**Comment by andreynering** [comment]
## Before

Screen Shot 2022-10-14 at 15 48 34

## After

Screen Shot 2022-10-14 at 15 48 53

---

As I said, I found it quite hard to see matched words. I'm using this on `settings.json` for now to override it:

```json
{
  "workbench.colorCustomizations": {
    "[Atom One Light]": {
      "editor.selectionHighlightBackground": "#eaeaeb"
    }
  }
}
```

**Pull request closed without merging**
